### ISSUE TITLE
result?

### ISSUE THREAD

**Issue by sassbalint** [theeluwin/wpe#1]
Thank you for this code. :smiley:

As I understand well, running `python3 main.py`:

```
# we (should) get "a a", "b", "c" as keywords!
```

But the result for me is:
```
[iter   0] freq     2	a + a
no pair with freq >= 2. early stopping...
```

Please help, what can be the problem.

**Comment by theeluwin** [comment]
The keyword list is saved in `result/keywords.txt`. I'll update the readme someday...
